---
kind: Namespace
metadata:
      name: %NAMESPACE
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: thebest
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: thebest
        tier: web
    spec:
      containers:
          - name: thebest
            image: %IMAGE
            ports:
                - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: thebest-svc
  labels:
    app: thebest
    tier: lb
spec:
  ports:
    # the port that this service should serve on
  - port: 80
    targetPort: 80
  type: NodePort
  selector:
    app: thebest
    tier: web
